### ISSUE TITLE
Add ability to import monsters

### ISSUE THREAD

**Issue by Zugyuk** [SteveWorcester/Roll20Roller#16]
HUGE FEATURE

Add monsters to import for GM ease of use.

**Comment by SteveWorcester** [comment]
The effort involved in this feature is massive, and will provide little benefit. Closing issue.

Reasoning behind little benefit: 
- Rolled actions are few on monster pages
- Regex to find every monster's rolls would be extremely complicated, and may causes errors due to fragility of page layouts when displaying monster data.
